### ISSUE TITLE
Stack error on very large schemas

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/schema#483]
#### Description 

- e.g. 489k LOC input types typescript file
- `RangeError: Maximum call stack size exceeded`

**Comment by mohsin51** [comment]
@jasonkuhrt i was going to open a ticket for this but saw it's already opened.
I'm having same issue in my schema, its very large there are around 200 complex models and it throws exception when i run backend server or try to generate artifacts, however as a way around i was able to run my server and generate artifacts by increasing the node stack size upto 1300 
here are some details about the stack
**Stack of error when i run server**
`/home/in01-nbk-741/Work/apps/intech-apps/node_modules/@nexus/schema/src/builder.ts:773
      fields: () => this.buildInputObjectFields(fields, inputObjectTypeConfig),
              ^
RangeError: Maximum call stack size exceeded
    at fields (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/@nexus/schema/src/builder.ts:773:15)
    at resolveThunk (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/definition.js:438:40)
    at defineInputFieldMap (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/definition.js:1056:18)
    at GraphQLInputObjectType.getFields (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/definition.js:1017:27)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:291:79)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
    at typeMapReducer (/home/in01-nbk-741/Work/apps/intech-apps/node_modules/graphql/type/schema.js:293:20)
`

**Comment by tom-sherman** [comment]
I would love to work on this but it's difficult to start without a repro, could you provide one or tell me how to generate one?
