### ISSUE TITLE
Error when using scalar as nexus method in interface definition

### ISSUE THREAD

**Issue by Fryuni** [graphql-nexus/schema#612]
When using the extended method inside interfaces definition nexus throws a `TypeError` when making the schema.

This is the scalar definition:
```typescript
scalarType({
    name: 'Instant',
    asNexusMethod: 'instant',
    description: 'Instant in milliseconds since Unix epoch',
    parseValue: (value: any) => (typeof value === 'number' ? Instant.fromEpochMillis(value) : null),
    serialize: value => (value instanceof Instant ? value.toMillis() : null),
});
```

This is the interface definition:
```typescript
interfaceType({
    name: 'Notification',
    definition: t => {
        console.log('id: ', t.id);
        t.id('id');
        console.log('instant: ', t.instant);
        t.instant('timestamp'); // Breaks in this line
    },
});
```

Log and error:
```
id:  [Function: id]
instant:  [Function (anonymous)]
id:  [Function: id]
instant:  undefined
TypeError: t.instant is not a function
    at Object.definition (/home/lotus/IsoWorkspaces/Croct/admin/backend/src/infrastructure/graphql/schema/workspace/schema.ts:44:11)
    at walkType (/home/lotus/IsoWorkspaces/Croct/admin/backend/node_modules/@nexus/schema/src/builder.ts:737:11)
    at /home/lotus/IsoWorkspaces/Croct/admin/backend/node_modules/@nexus/schema/src/builder.ts:741:7
    at Array.forEach (<anonymous>)
    at SchemaBuilder.checkForInterfaceCircularDependencies (/home/lotus/IsoWorkspaces/Croct/admin/backend/node_modules/@nexus/schema/src/builder.ts:740:29)
    at SchemaBuilder.getFinalTypeMap (/home/lotus/IsoWorkspaces/Croct/admin/backend/node_modules/@nexus/schema/src/builder.ts:802:10)
    at makeSchemaInternal (/home/lotus/IsoWorkspaces/Croct/admin/backend/node_modules/@nexus/schema/src/builder.ts:1546:92)
    at Object.makeSchema (/home/lotus/IsoWorkspaces/Croct/admin/backend/node_modules/@nexus/schema/src/builder.ts:1585:49)
    at Object.<anonymous> (/home/lotus/IsoWorkspaces/Croct/admin/backend/src/infrastructure/graphql/definition.ts:7:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

The interface definition is being called twice and on the second run the extended method is undefined.

**Comment by Fryuni** [comment]
Using `t.instant?.('timestamp')` to skip when the method is not defined works. Without the error the definition function is actually called 3 times and the third time the function is defined. The last one is the one used on the schema, resolvers, etc.
