### ISSUE TITLE
Nexus won't generate just one type named "Configuration"

### ISSUE THREAD

**Issue by hyperxpizza** [graphql-nexus/schema#686]
I have an app which is using prisma and nexus schema. Nexus works fine, but it won't generate just one type named Configuration.

index.ts:
```
import { makeSchema } from "@nexus/schema"
import { nexusSchemaPrisma } from "nexus-plugin-prisma/schema"
import { GraphQLServer } from "graphql-yoga"
import { createContext } from './context'
import { APP_SECRET } from './utils'
import { permissions } from "./permissions";
//import { transformConfigurations } from "./transform/Transformer";
import * as express from "express";
import * as bodyParser from "body-parser";
import * as jwt from "express-jwt";
import * as cors from "cors";

// gql types
import { AuthPayload } from './types/AuthPayload'
import { Category } from './types/Category'
import { ColourCombination } from './types/ColourCombination'
import { CompareElement } from './types/CompareElement'
import { Configuration } from './types/Configuration'
import { ConfigurationElements } from './types/ConfigurationElements'
import { Drivetrain } from './types/Drivetrain'
import { RenamedEngine } from './types/Engine'
import { Modell } from './types/Modell'
import { ModelVariant } from './types/ModelVariant'
import { Mutation } from './types/Mutations'
import { Query } from './types/Queries'
import { SpecLevel } from './types/SpecLevel'
import { User } from './types/User'
import { WhereConfigurationInput } from './types/WhereConfigurationInput'


// Initialize Nexus/GQL schema
const schema = makeSchema({
  types: [Query, Mutation, AuthPayload, Configuration, Category, ColourCombination, CompareElement, ConfigurationElements, Drivetrain, RenamedEngine, Modell, ModelVariant, SpecLevel, User, WhereConfigurationInput],
  //types: [Configuration],
  plugins: [nexusSchemaPrisma()],
  outputs: {
    schema: __dirname + '/schema.graphql',
    typegen: __dirname + '/nexus.ts',
  },
  typegenAutoConfig: {
    contextType: "Context.Context",
    sources: [
      {
        source: "@prisma/client",
        alias: "prisma",
      },
      {
        source: require.resolve("./context"),
        alias: "Context",
      },
    ],
  },
})
```

types/Configuration.ts
```
import { objectType } from '@nexus/schema'

export const Configutation = objectType({
    name:'Configuration',
    definition(t){
        t.model.id()
        t.model.pdbCreationDate()
        t.model.colourCombination()
        t.model.drivetrain()
        t.model.modell()
        t.model.modelVariant()
        t.model.specLevel()
    }
})
```

terminal output:
```bash
[INFO] 12:51:45 ts-node-dev ver. 1.0.0 (using ts-node ver. 9.0.0, typescript ver. 3.9.7)
Error: 
- Missing type Configuration, did you forget to import a type to the root query or mean ConfigurationElements, WhereConfigurationInput?
    at Object.assertNoMissingTypes (/home/hyperxpizza/programowanie/mip/reporting-system/master-cc-backend/cc-backend/node_modules/@nexus/schema/src/utils.ts:323:11)
    at Object.makeSchema (/home/hyperxpizza/programowanie/mip/reporting-system/master-cc-backend/cc-backend/node_modules/@nexus/schema/src/builder.ts:1616:3)
    at Object.<anonymous> (/home/hyperxpizza/programowanie/mip/reporting-system/master-cc-backend/cc-backend/src/index.ts:32:16)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module._compile (/home/hyperxpizza/programowanie/mip/reporting-system/master-cc-backend/cc-backend/node_modules/source-map-support/source-map-support.js:541:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-8686021251746991.js:57:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-8686021251746991.js:59:20)
    at Object.nodeDevHook [as .ts] (/home/hyperxpizza/programowanie/mip/reporting-system/master-cc-backend/cc-backend/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
[ERROR] 12:51:46 Error: 
- Missing type Configuration, did you forget to import a type to the root query or mean ConfigurationElements, WhereConfigurationInput?
```

**Comment by hyperxpizza** [comment]
can be deleted, typo...
